typography_spectrum: 0.3700229290407151
color:
  brandStrength: 0.4972320895176381
  lightness: 0.030698921531438828
  saturation: 0.39500754489563406
  rhythmicContrast: 0.9354851532261819
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
opengraph:
  type: Photography Page
  appId: 'https://www.facebook.com/KarisaMirandaPhotography/'
layout_spectrum: 0.7638558887410909
author:
  name: Karisa Miranda
  email: photography@karisamiranda.com
  url: www.karisamiranda.com
name: Beyond Vignette
title: Karisa Miranda
